# notes: setting duration to -1 will equate to INT_MAX-1
effects:
  # ABSORPTION
  # BAD_OMEN
  # BLINDNESS
  # CONDUIT_POWER
  # CONFUSION
  # DAMAGE_RESISTANCE
  # DARKNESS
  # DOLPHINS_GRACE
  # FAST_DIGGING
  # FIRE_RESISTANCE
  # GLOWING
  # HARM
  # HEAL
  # HEALTH_BOOST
  # HERO_OF_THE_VILLAGE
  # HUNGER
  # INCREASE_DAMAGE
  # INVISIBILITY
  # JUMP
  # LEVITATION
  # LUCK
  # NIGHT_VISION
  # POISON
  # REGENERATION
  # SATURATION
  # SLOW
  # SLOW_DIGGING
  # SLOW_FALLING
  # SPEED
  # UNLUCK
  # WATER_BREATHING
  # WEAKNESS
  # WITHER
  - { effects: conduit_power, duration: -1, amplifier: 0, ambient: false, particles: false}